# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PowerShell@2
  inputs:
    filePath: 'https://ansafone-my.sharepoint.com/:u:/r/personal/jason_wright_ansafone_com/Documents/Microsoft%20Teams%20Chat%20Files/SimpleMonitorScript.ps1?csf=1&web=1&e=mRtBs5'